name: Release CI

on:
  push:
    tags:
      - "v*"

jobs:
  build-winform:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore "./src/IME WL Converter Win"

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish "./src/IME WL Converter Win"

      - name: Archive Release
        run: 7z a -tzip imewlconverter_Windows.zip publish/

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          includeInvalidCommits: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "imewlconverter_Windows.zip"
          allowUpdates: true
          body: |
            ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-cmd:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/ImeWlConverterCmd

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ./src/ImeWlConverterCmd

      - name: Archive Release
        run: tar -czf imewlconverter_${{ runner.os }}.tar.gz publish/*

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          includeInvalidCommits: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "imewlconverter_${{ runner.os }}.tar.gz"
          allowUpdates: true
          body: |
            ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
